version: '3.8'

services:
  # The Database Service
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
