services:
  # Postgres Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # For local db debugging

  # Flask API
  backend:
    image: pasrichanimit/web-forum-backend:latest
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://dbuser:dbpassword@db:5432/mydb
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # React App
  frontend:
    image: pasrichanimit/web-forum-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data: